# Generated by Django 4.1.1 on 2022-11-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(upload_to='cursos'),
        ),
    ]
