# Generated by Django 4.1.1 on 2022-11-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
