# Generated by Django 4.1.1 on 2022-11-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='contenido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
