# Generated by Django 4.1.1 on 2022-12-01 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0005_cursos_created_cursos_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscripcion',
                'verbose_name_plural': 'inscripciones',
                'db_table': 'inscripciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos')),
                ('inscripcion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linea Inscripcion',
                'verbose_name_plural': 'Lineas Inscripciones',
                'db_table': 'lineainscripciones',
                'ordering': ['id'],
            },
        ),
    ]
